### ISSUE TITLE
fatal error: termbox.h: No such file or directory

### ISSUE THREAD

**Issue by euanworkman** [dom96/nimbox#7]
When attempting to nimbox, after installation through nimble, I am greeted with the following error:

```
Error: execution of an external compiler program 'gcc -c  -w  -I/home/ewpolly/.choosenim/toolchains/nim-0.19.0/lib -o /home/ewpolly/.cache/nim/MusicInfo_d/nimbox_nimbox.c.o /home/ewpolly/.cache/nim/MusicInfo_d/nimbox_nimbox.c' failed with exit code: 1

/home/ewpolly/.cache/nim/MusicInfo_d/nimbox_nimbox.c:11:10: fatal error: termbox.h: No such file or directory
 #include "termbox.h"
          ^~~~~~~~~~~
compilation terminated.
```

Is there anything which I need to additionally install?
I've tried install termbox from https://github.com/nsf/termbox using the waf scripts, and deleted ~/.cache/nim, however I still receive this issue.

**Comment by zetashift** [comment]
On what platform are you? 
You probably need to put this baby: https://github.com/nsf/termbox/blob/master/src/termbox.h beside your source files

**Comment by euanworkman** [comment]
Thanks for your help, I managed to solve the issue, it turns out that I hasn't installed termbox correctly after all. Sorry for taking your time!
